### ISSUE TITLE
Unhandled 'error' event from MongoDB driver

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/itmat-broker#706]
```
[Thu, 06 Aug 2020 11:20:42 GMT] me polling for new jobs of type ALL.
[Thu, 06 Aug 2020 11:22:22 GMT] me polling for new jobs of type ALL.
[Thu, 06 Aug 2020 11:24:02 GMT] me polling for new jobs of type ALL.
[Thu, 06 Aug 2020 11:25:42 GMT] me polling for new jobs of type ALL.
[Thu, 06 Aug 2020 11:27:22 GMT] me polling for new jobs of type ALL.
[Thu, 06 Aug 2020 11:29:02 GMT] me polling for new jobs of type ALL.
[Thu, 06 Aug 2020 11:30:42 GMT] me polling for new jobs of type ALL.
[Thu, 06 Aug 2020 11:32:22 GMT] me polling for new jobs of type ALL.
events.js:292
      throw er; // Unhandled 'error' event
      ^

MongoServerSelectionError: connect ECONNREFUSED 172.x.x.x:27017
    at Timeout._onTimeout (/itmat-base/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on ChangeStream instance at:
    at processError (/itmat-base/node_modules/mongodb/lib/change_stream.js:567:38)
    at ChangeStreamCursor.<anonymous> (/itmat-base/node_modules/mongodb/lib/change_stream.js:436:5)
    at ChangeStreamCursor.emit (events.js:315:20)
    at /itmat-base/node_modules/mongodb/lib/core/cursor.js:343:16
    at /itmat-base/node_modules/mongodb/lib/core/cursor.js:745:9
    at /itmat-base/node_modules/mongodb/lib/change_stream.js:330:9
    at Object.callback (/itmat-base/node_modules/mongodb/lib/core/cursor.js:432:11)
    at Timeout._onTimeout (/itmat-base/node_modules/mongodb/lib/core/sdam/topology.js:435:25)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map { '172.x.x.x:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 8
  }
}
```

**Comment by sou-chon** [comment]
what would this be due to?

**Comment by fguitton** [comment]
I'm not quite sure, I guess the problem is not so much that the connection to mongo dropped, but that the server completely crashed when that happened. So we probably need to look into this further later.
